<h1>Asignments</h1>

<h2>Module 4: Data Structure Assignment </h2>

<h4>Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True, 8.10. 
<h4>a. Now in the ‘myList’, append these values: 30,40  
<h4>b. After that reverse the elements of the ‘myList’ and store that in ‘reversedList’ 

In [1]:
myList = [10,20,30,'apple', True, 8.10]

In [2]:
myList

[10, 20, 30, 'apple', True, 8.1]

In [3]:
myList.append(30)
myList.append(40)

In [4]:
myList

[10, 20, 30, 'apple', True, 8.1, 30, 40]

In [5]:
def Reverse(List):
    return [x for x in reversed(List)]

In [6]:
reversedList = Reverse(myList)

In [7]:
print(myList, "\n", reversedList)

[10, 20, 30, 'apple', True, 8.1, 30, 40] 
 [40, 30, 8.1, True, 'apple', 30, 20, 10]


<h4>Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’. 
<h4>a. After that eliminate the ‘text’ value form the dictonary. 
<h4>b. Add ‘features’ in the dictonary. 
<h4>c. Fetch the ‘data’ element from the dictonary and display it in the output. 

In [8]:
dictionary = {"1":"data", "2": "information", "3": "text"}

In [9]:
del(dictionary["3"])

In [10]:
dictionary

{'1': 'data', '2': 'information'}

In [11]:
dictionary["4"] = "features"

In [12]:
dictionary

{'1': 'data', '2': 'information', '4': 'features'}

In [13]:
for key, value in dictionary.items():
    if(value == "data"):
        print(f"{key}, {value}")



1, data


<h4>Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple

In [14]:
Tuple = (1,2,3,"apple","mango")
my_tuple = Tuple

In [15]:
my_tuple

(1, 2, 3, 'apple', 'mango')

<h4>Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50 
<h4>a. Find the minimum value from the numeric_tuple. 
<h4>b. Concatenate my_tuple with numeric_tuple and store the result in r1. 
<h4>c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.

In [16]:
numeric_tuple = (10,20,30,40,50)

In [17]:
min(numeric_tuple)

10

In [18]:
r1 = my_tuple + numeric_tuple

In [19]:
r1

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)

In [20]:
newdupli = my_tuple * 2

In [21]:
newdupli

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')

<h4>Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to 
<h4>contains{2,3,7,6,1} 
<h4>a. Perform the below operation: 
<h4>a. set1 union set2 
<h4>b. set1 intersection set2   
<h4>c. set1 difference set2 

In [22]:
set1 = {1,2,3,4,5}
set2 = {2,3,7,6,1}

In [23]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [24]:
set1.intersection(set2)

{1, 2, 3}

In [25]:
set1.difference(set2)

{4, 5}

<h2>Module 4: Numpy Assignment 

In [26]:
import numpy as np

<h4>Create a 3x3 matrix array with values ranging from 2 to 10.

In [27]:
arr = np.random.randint(2, 10, (3,3))

In [28]:
arr

array([[6, 6, 6],
       [2, 3, 6],
       [7, 4, 7]])

or

In [29]:
arr = np.arange(2,11).reshape(3,3)

In [30]:
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

<h4>Create a numpy array having user input values and convert the integer type to the float type of the elements of the  array. For instance: 
<h4>Original array 
<h4>[1, 2, 3, 4] 
<h4>Array converted to a float type: 
<h4>[ 1. 2. 3. 4.] 


In [31]:
print("Enter the array values. Press q to end")
arr = []
while(True):
    num = input()
    if(num == 'q'):
        break
    arr.append(int(num))

arr = np.array(arr)
arr

Enter the array values. Press q to end
45
56
88
41
56
q


array([45, 56, 88, 41, 56])

In [32]:
arr.astype(float)

array([45., 56., 88., 41., 56.])

<h4>Write a Numpy program to append values to the end of an array. For instance: 
<h4>Original array: 
<h4>[10, 20, 30] 
<h4>After append values to the end of the array: 
<h4>[10 20 30 40 50 60 70 80 90] 

In [33]:
print("Enter the array1 values. Press q to end")
arr1 = []
while(True):
    num = input()
    if(num == 'q'):
        break
    arr1.append(int(num))

arr1 = np.array(arr1)

print("Enter the array2 values. Press q to end")
arr2 = []
while(True):
    num = input()
    if(num == 'q'):
        break
    arr2.append(int(num))

arr2 = np.array(arr2)

Enter the array1 values. Press q to end
56
96
85
74
12
q
Enter the array2 values. Press q to end
45
63
89
78
32
q


In [34]:
arr1 = np.append(arr1,arr2)

In [35]:
arr1

array([56, 96, 85, 74, 12, 45, 63, 89, 78, 32])

<h4>Create two numpy arrays and add the elements of both the arrays and store the result in sumArray.

In [36]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [37]:
sumArray = np.array([])
if(arr1.shape == arr2.shape):
    sumArray = arr1 + arr2

sumArray

array([ 7,  9, 11, 13, 15])

<h4>Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform the following tasks: 
<h4>a. Extract the 1st row from the array. 
<h4>b. Extract the last element from the array. 

In [38]:
array1 = np.linspace(10,90,9).reshape(3,3).astype(int)

In [39]:
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
array1[0]

array([10, 20, 30])

In [41]:
array1[2][2]

90